--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUESTION
--------------------------------------------------------

  CREATE TABLE "C##ORA_USER"."QUESTION" 
   (	"M_ID" VARCHAR2(20 BYTE), 
	"PROB_NUM" NUMBER, 
	"QST_DATE" VARCHAR2(25 BYTE), 
	"QST_BODY" CLOB, 
	"QST_TITLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("QST_BODY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into C##ORA_USER.QUESTION
SET DEFINE OFF;
Insert into C##ORA_USER.QUESTION (M_ID,PROB_NUM,QST_DATE,QST_TITLE) values ('123',121,'20/07/22 16:22:54','이러쿵
저러쿵
아무말');
Insert into C##ORA_USER.QUESTION (M_ID,PROB_NUM,QST_DATE,QST_TITLE) values ('123',128,'20/07/22 16:34:21','진짜 못풀게 만들어놨네;');
Insert into C##ORA_USER.QUESTION (M_ID,PROB_NUM,QST_DATE,QST_TITLE) values ('123',124,'20/07/21 13:31:50','아 124번 개어렵넹 - 제목 수정');
--------------------------------------------------------
--  DDL for Index PK_QUESTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ORA_USER"."PK_QUESTION" ON "C##ORA_USER"."QUESTION" ("M_ID", "PROB_NUM", "QST_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QUESTION
--------------------------------------------------------

  ALTER TABLE "C##ORA_USER"."QUESTION" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION" MODIFY ("PROB_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION" MODIFY ("QST_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION" MODIFY ("QST_BODY" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY ("M_ID", "PROB_NUM", "QST_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ORA_USER"."QUESTION" MODIFY ("QST_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table QUESTION
--------------------------------------------------------

  ALTER TABLE "C##ORA_USER"."QUESTION" ADD CONSTRAINT "FK_QST_M_ID" FOREIGN KEY ("M_ID")
	  REFERENCES "C##ORA_USER"."MEMBER" ("M_ID") ENABLE;
  ALTER TABLE "C##ORA_USER"."QUESTION" ADD CONSTRAINT "FK_QST_PROB_NUM" FOREIGN KEY ("PROB_NUM")
	  REFERENCES "C##ORA_USER"."PROBLEM" ("PROB_NUM") ENABLE;
