--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUESTION_COMMENT
--------------------------------------------------------

  CREATE TABLE "C##ORA_USER"."QUESTION_COMMENT" 
   (	"Q_ID" VARCHAR2(20 BYTE), 
	"QC_ID" VARCHAR2(20 BYTE), 
	"PROB_NUM" NUMBER, 
	"QST_DATE" VARCHAR2(25 BYTE), 
	"QC_DATE" VARCHAR2(25 BYTE), 
	"QC_BODY" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ORA_USER.QUESTION_COMMENT
SET DEFINE OFF;
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','star',124,'20/07/21 13:31:50','20/07/21 15:25:25','풀고나 말하시지!');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','노승현',124,'20/07/21 13:31:50','20/07/23 02:55:23','결과는 과연..?');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','노승현',124,'20/07/21 13:31:50','20/07/23 02:56:54','두둔!');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','노승현',128,'20/07/22 16:34:21','20/07/23 02:59:25','그 정도에요?');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','star',121,'20/07/22 16:22:54','20/07/23 03:05:07','뭘 도와 드릴까요?');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','123',124,'20/07/21 13:31:50','20/07/21 13:45:26','답변하신 star님.. 말이 너무 심하시네요.');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','123',124,'20/07/21 13:31:50','20/07/23 02:46:23','답 좀 해주세요ㅠㅠㅠ');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','star',121,'20/07/22 16:22:54','20/07/23 03:06:10','이러쿵 저러쿵..?');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','노승현',128,'20/07/22 16:34:21','20/07/23 03:12:30','어떻길래요?');
Insert into C##ORA_USER.QUESTION_COMMENT (Q_ID,QC_ID,PROB_NUM,QST_DATE,QC_DATE,QC_BODY) values ('123','star',121,'20/07/22 16:22:54','20/07/23 03:10:25','아무도..?');
--------------------------------------------------------
--  DDL for Index PK_QUESTION_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ORA_USER"."PK_QUESTION_COMMENT" ON "C##ORA_USER"."QUESTION_COMMENT" ("Q_ID", "QC_ID", "PROB_NUM", "QST_DATE", "QC_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QUESTION_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" MODIFY ("Q_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" MODIFY ("QC_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" MODIFY ("PROB_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" MODIFY ("QST_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" MODIFY ("QC_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" MODIFY ("QC_BODY" NOT NULL ENABLE);
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" ADD CONSTRAINT "PK_QUESTION_COMMENT" PRIMARY KEY ("Q_ID", "QC_ID", "PROB_NUM", "QST_DATE", "QC_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUESTION_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" ADD CONSTRAINT "FK_QC_Q_ID" FOREIGN KEY ("Q_ID")
	  REFERENCES "C##ORA_USER"."MEMBER" ("M_ID") ENABLE;
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" ADD CONSTRAINT "FK_QC_QC_ID" FOREIGN KEY ("QC_ID")
	  REFERENCES "C##ORA_USER"."MEMBER" ("M_ID") ENABLE;
  ALTER TABLE "C##ORA_USER"."QUESTION_COMMENT" ADD CONSTRAINT "FK_QC_PROB_NUM" FOREIGN KEY ("PROB_NUM")
	  REFERENCES "C##ORA_USER"."PROBLEM" ("PROB_NUM") ENABLE;
